### PR TITLE
Add mame cores

### PR DESCRIPTION
**Pull request by fetzerch**
@garbear You probably want to build this branch first before merging. They've got a tendency to burn a lot of cpu and memory.

### CODE REVIEW

**Comment by garbear** [comment]
I attempted compilation of all the MAME cores. mame2000 fails to build with this error:

```
Linking mame2000_libretro.so...
./src/drivers/taitosj.o: In function `check_sprite_sprite_collision':
/home/garrett/Documents/binary-addons/build/mame2000/src/mame2000/src/drivers/../vidhrdw/taitosj.c:488: undefined reference to `get_sprite_xy'
/home/garrett/Documents/binary-addons/build/mame2000/src/mame2000/src/drivers/../vidhrdw/taitosj.c:496: undefined reference to `get_sprite_xy'
./src/drivers/taitosj.o: In function `calculate_sprites_areas':
/home/garrett/Documents/binary-addons/build/mame2000/src/mame2000/src/drivers/../vidhrdw/taitosj.c:533: undefined reference to `get_sprite_xy'
./src/drivers/taitosj.o: In function `drawsprites':
/home/garrett/Documents/binary-addons/build/mame2000/src/mame2000/src/drivers/../vidhrdw/taitosj.c:670: undefined reference to `get_sprite_xy'
collect2: error: ld returned 1 exit status
Makefile:369: recipe for target 'mame2000_libretro.so' failed
make[7]: *** [mame2000_libretro.so] Error 1
CMakeFiles/mame2000.dir/build.make:110: recipe for target 'mame2000/src/mame2000-stamp/mame2000-build' failed
make[6]: *** [mame2000/src/mame2000-stamp/mame2000-build] Error 2
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/mame2000.dir/all' failed
make[5]: *** [CMakeFiles/mame2000.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make[4]: *** [all] Error 2
CMakeFiles/mame2000.dir/build.make:110: recipe for target 'build/mame2000/src/mame2000-stamp/mame2000-build' failed
make[3]: *** [build/mame2000/src/mame2000-stamp/mame2000-build] Error 2
CMakeFiles/Makefile2:382: recipe for target 'CMakeFiles/mame2000.dir/all' failed
make[2]: *** [CMakeFiles/mame2000.dir/all] Error 2
CMakeFiles/Makefile2:394: recipe for target 'CMakeFiles/mame2000.dir/rule' failed
make[1]: *** [CMakeFiles/mame2000.dir/rule] Error 2
Makefile:235: recipe for target 'mame2000' failed
make: *** [mame2000] Error 2
```

game.libretro.mame2003_plus should be game.libretro.mame2003-plus for consistency.

mame OG fails to link after exhausting all 16GB of memory on my desktop.

2003, 2003-plus, 2010, 2014 and 2016 all build successfully.

**Comment by garbear** [comment]
That was for debug builds. I'll try mame OG in release mode and see if it builds without exhausting RAM

EDIT: MAME builds in release and produces a 350MB x64 binary. I haven't tried MAME 2016 in release, but the debug build produces a 3.1GB .so

**Comment by 5schatten** [comment]
You should focus on mame 2003/2003-plus (0.78) & mame 2010 (0.139) for low end systems like RPi and common ARM based boards & 2014 (0.159) & 2016 (0.174)  for recent x86 ones. Mame itself is the bleeding edge stuff that needs really recent romsets to work.

Since you also offer fb-alpha you already have a core that is able to play bleeding edge stuff and is synced to quite recent mame rom sets (~0.197)

**Comment by fetzerch** [comment]
@garbear, according to @Rechi this is needed so that the cores are built and uploaded to the binary repo

**Comment by Rechi** [comment]
It's not necessarily required, but I only allowed addons listed in retroplayer branch for now.

If there is a really good reason to not merge this, I can still add them. Just wanted to avoid confusion about how to build those (if not in main branch).

**Comment by garbear** [comment]
I delayed merging this because they burned a lot of jenkins time for all my releases. Now that binary add-ons are built separately this can go it.

**Pull request merged**
